/**
 * Retirement Life: a lighter, non-financial section. A short scored quiz
 * sorts you into one of eight retirement "personalities," each with a
 * playful tagline and a long list of activities to steal ideas from.
 * Purely for fun/inspiration — no numbers, no advice.
 */

const QUIZ_TYPE_ORDER = [
  "adventurer",
  "creator",
  "connector",
  "sage",
  "homebody",
  "competitor",
  "giver",
  "entrepreneur",
];

const RETIREMENT_PERSONALITIES = [
  {
    key: "adventurer",
    emoji: "🗺️",
    label: "The Adventurer",
    color: "#1b8a9c",
    tagline: "Home is wherever the itinerary says next.",
    description:
      "You didn't retire to sit still. The whole point was finally having time to go everywhere you've been bookmarking for thirty years. Your passport has more stamps than your fridge has magnets.",
    activities: [
      "RV or van-life road trips across the country",
      "Slow travel — a month at a time in a new city abroad",
      "National Parks passport challenge (all 63 and counting)",
      "Section-hiking the Appalachian or Pacific Crest Trail",
      "Scuba diving certification",
      "Learning to sail (or just buying a boat)",
      "Motorcycle touring",
      "Geocaching across your state",
      "Working holidays and volunteer stints abroad (WWOOF farms)",
      "Cruise repositioning trips — cheap one-way sailings between seasons",
      "Heritage or ancestry travel to where your family's from",
      "Overlanding — off-road camping expeditions",
      "Hot air ballooning or skydiving, at least once, for the story",
      "Photography trips built entirely around golden hour",
    ],
    budgetRange: { low: 8000, high: 25000 },
    gettingStarted: [
      { text: "Scuba: a PADI or NAUI Open Water certification takes 3–4 days and runs roughly $400–600 — most local dive shops offer it.", url: "https://www.padi.com" },
      { text: "Sailing: a US Sailing basic keelboat course is a common first step, usually a single weekend.", url: "https://www.ussailing.org" },
      { text: "RVing: many RV clubs and dealers run beginner caravanning workshops before you buy anything." },
      { text: "Long-distance hiking: outdoor retailers' gear and trip-planning clinics are a low-stakes way to prep before a big one." },
    ],
  },
  {
    key: "creator",
    emoji: "🎨",
    label: "The Creator",
    color: "#7b5ea7",
    tagline: "Retirement is just unlimited studio time.",
    description:
      "You've always needed to make something with your hands — now you get to do it without squeezing it into weekends. A pile of half-finished projects isn't a problem, it's a lifestyle.",
    activities: [
      "Painting or watercolor classes",
      "Pottery and ceramics at a community studio",
      "Woodworking shop projects",
      "Quilting or fiber arts",
      "Writing the memoir (or novel) you've been putting off",
      "Learning an instrument, finally",
      "Joining a community choir or band",
      "Blacksmithing or metalworking",
      "Jewelry making",
      "Home brewing or winemaking",
      "Furniture restoration",
      "Starting a podcast or YouTube channel",
      "Stained glass or mosaic work",
      "Calligraphy and hand-lettering",
    ],
    budgetRange: { low: 1500, high: 6000 },
    gettingStarted: [
      { text: "Most community colleges have a low-cost continuing-ed catalog — pottery, woodworking, and jewelry classes often run $50–200." },
      { text: "Local makerspaces offer access to kilns, laser cutters, and wood shops without buying your own equipment." },
      { text: "For writing, a local library writing group is a free way to test the waters before a paid workshop." },
      { text: "Community music schools run adult-beginner classes with no audition required." },
    ],
  },
  {
    key: "connector",
    emoji: "🎉",
    label: "The Connector",
    color: "#e8871e",
    tagline: "A calendar with nobody in it is a problem to solve.",
    description:
      "For you, retirement isn't about escaping people — it's about finally having enough time for all of them. If there's a gathering happening, there's a good chance you organized it.",
    activities: [
      "Hosting a recurring supper club",
      "Starting or joining a lively book club",
      "Weekly bridge, mahjong, or poker nights",
      "Becoming a town or museum greeter",
      "Organizing the whole extended family's reunion",
      "Ballroom or line dancing lessons",
      "Wine or whiskey tasting groups",
      "Docent tours at a local museum or garden",
      "Game nights that get a little too competitive",
      "Volunteering at community festivals",
      "Joining a Rotary, Lions, or Elks club",
      "Group trips planned entirely around who's coming",
      "Starting a neighborhood association",
      "Running a meal train for new parents or the newly widowed",
    ],
    budgetRange: { low: 2000, high: 7000 },
    gettingStarted: [
      { text: "No group exists yet? Starting one on Meetup takes minutes.", url: "https://www.meetup.com" },
      { text: "VolunteerMatch and a local Rotary, Lions, or Elks chapter are easy on-ramps to a built-in social calendar.", url: "https://www.volunteermatch.org" },
      { text: "Ballroom and line-dancing studios almost always offer a free or cheap intro class before you commit." },
    ],
  },
  {
    key: "sage",
    emoji: "📚",
    label: "The Sage",
    color: "#2f6690",
    tagline: "You retired from work, not from learning.",
    description:
      "You've got the reading list, the course catalog, and the genuine curiosity to actually use them. No test at the end — that's the best part.",
    activities: [
      "Auditing university courses (many let seniors sit in free)",
      "Osher Lifelong Learning Institute (OLLI) classes",
      "Finally getting fluent in that language",
      "Genealogy research — building out the full family tree",
      "A book club that only reads the hard stuff",
      "Museum lecture series",
      "Becoming a docent or historical tour guide",
      "Writing the definitive history of your town",
      "Chess club (or finally getting good at it)",
      "Documentary nights with real discussion afterward",
      "Online courses, just because a topic looked interesting",
      "Amateur astronomy and stargazing",
      "Birdwatching with a proper field journal",
      "Learning to code, purely for the puzzle of it",
    ],
    budgetRange: { low: 500, high: 3000 },
    gettingStarted: [
      { text: "Osher Lifelong Learning Institutes (OLLI) run through 125+ universities nationwide — no degree required, low annual fee. Search \"OLLI\" plus your nearest university." },
      { text: "Coursera and edX let you audit most courses free; pay only if you want a certificate.", url: "https://www.coursera.org" },
      { text: "Many public libraries run free lecture series, language classes, and museum-pass programs — check yours first." },
    ],
  },
  {
    key: "homebody",
    emoji: "🌱",
    label: "The Homebody",
    color: "#a3763f",
    tagline: "The best trip is twenty feet into the backyard.",
    description:
      "You don't need a flight to feel like you got away — just good dirt, a working oven, and nowhere else to be. Home is the project now.",
    activities: [
      "A serious vegetable garden — maybe a small homestead",
      "Beekeeping",
      "Canning and preserving the harvest",
      "Sourdough baking (a real, maintained starter)",
      "Backyard chickens",
      "Landscaping and redesigning your own yard",
      "Building a greenhouse",
      "A growing houseplant collection",
      "Cooking through a cookbook, one recipe a week",
      "Slow home renovation projects, done right this time",
      "Restoring antique furniture",
      "Composting and permaculture design",
      "Flower arranging and a cutting garden",
      "Cheese-making",
    ],
    budgetRange: { low: 1000, high: 5000 },
    gettingStarted: [
      { text: "Master Gardener certification runs through your county's Cooperative Extension office — a free/low-cost, university-affiliated network in nearly every county." },
      { text: "The same extension offices often teach canning, beekeeping, and food-safety basics, frequently for free." },
      { text: "Community college culinary continuing-ed classes are a low-stakes way to level up cooking without a full program." },
    ],
  },
  {
    key: "competitor",
    emoji: "🏆",
    label: "The Competitor",
    color: "#b8960c",
    tagline: "There's a leaderboard somewhere, and you intend to be on it.",
    description:
      "Retirement didn't retire your competitive streak. You just found new arenas — better ones, with more trophies and far fewer performance reviews.",
    activities: [
      "Pickleball leagues (the retiree sport of the moment)",
      "Golf leagues and member-guest tournaments",
      "Senior Olympics",
      "Training for a marathon or half-marathon",
      "A serious cycling club",
      "Tennis leagues (there's a USTA bracket for every level)",
      "Masters swim teams",
      "A rec softball or kickball league",
      "Fishing tournaments",
      "Disc golf",
      "Bowling leagues",
      "Triathlon training",
      "Rock climbing at the local gym",
      "Table tennis clubs — more competitive than you'd think",
    ],
    budgetRange: { low: 2000, high: 8000 },
    gettingStarted: [
      { text: "USA Pickleball's site lists local leagues and beginner clinics by zip code.", url: "https://www.usapickleball.org" },
      { text: "The National Senior Games (biennial, ages 50+) has state qualifying events most years — a fun target to train toward.", url: "https://www.nsga.com" },
      { text: "Municipal parks & rec departments run inexpensive adult sports leagues — usually cheaper than private clubs, a good first step." },
    ],
  },
  {
    key: "giver",
    emoji: "❤️",
    label: "The Giver",
    color: "#c2455d",
    tagline: "You're still clocking in — just not for a paycheck.",
    description:
      "Purpose, for you, has always meant being useful to somebody. Retirement just freed up more hours to actually do it.",
    activities: [
      "Meals on Wheels delivery",
      "Hospital or hospice volunteering",
      "Tutoring or adult literacy programs",
      "Habitat for Humanity builds",
      "Animal shelter volunteering",
      "Becoming a CASA (court advocate for children)",
      "Disaster relief volunteering (Red Cross)",
      "Mentoring young entrepreneurs through SCORE",
      "Serving on a nonprofit board",
      "Food bank volunteering",
      "Environmental cleanup crews",
      "Free tax prep for low-income families (VITA)",
      "Prison literacy or re-entry programs",
      "Volunteer mediation or conflict resolution",
    ],
    budgetRange: { low: 500, high: 3000 },
    gettingStarted: [
      { text: "VolunteerMatch lists vetted opportunities by cause and time commitment.", url: "https://www.volunteermatch.org" },
      { text: "BoardSource is a good starting point if nonprofit board service interests you.", url: "https://www.boardsource.org" },
      { text: "Meals on Wheels America has a chapter locator if meal delivery appeals.", url: "https://www.mealsonwheelsamerica.org" },
    ],
  },
  {
    key: "entrepreneur",
    emoji: "💼",
    label: "The Entrepreneur",
    color: "#445d76",
    tagline: "You didn't retire. You just fired your boss.",
    description:
      "Slowing down was never really the plan. You've got one more idea in you — maybe several — and now nobody's stopping you from trying.",
    activities: [
      "Consulting in your old field, on your own schedule",
      "Starting an Etsy shop",
      "Buying into a franchise",
      "Angel investing or mentoring startups",
      "Becoming a landlord (real estate investing)",
      "House flipping",
      "Freelance writing or editing",
      "Seasonal tax-season work",
      "Substitute teaching",
      "Becoming a notary public on the side",
      "Rideshare or delivery driving, part-time",
      "Paid public speaking or workshops",
      "Self-publishing books",
      "Running a food truck or pop-up",
    ],
    budgetRange: { low: 3000, high: 20000 },
    gettingStarted: [
      { text: "SCORE offers free one-on-one mentoring backed by the SBA — a strong first stop before spending anything.", url: "https://www.score.org" },
      { text: "The SBA's Learning Center has free courses on licensing, business structure, and basic finance.", url: "https://www.sba.gov" },
      { text: "Licensing requirements vary a lot by state and industry — start with your Secretary of State's business registration site." },
    ],
  },
];

const QUIZ_QUESTIONS = [
  {
    question: "A free Saturday with nothing on the calendar — what's your first move?",
    options: [
      { type: "adventurer", text: "Load up the car for a spontaneous road trip" },
      { type: "creator", text: "Disappear into the garage or studio and make something" },
      { type: "connector", text: "Call a few friends and get a group together" },
      { type: "sage", text: "Sink into a documentary or a stack of books" },
      { type: "homebody", text: "Putter in the garden or finally fix that shelf" },
      { type: "competitor", text: "Get a workout, a match, or a round of golf in" },
      { type: "giver", text: "See who could use a hand today" },
      { type: "entrepreneur", text: "Chase down an idea that's been nagging at me" },
    ],
  },
  {
    question: "Which headline would you click on immediately?",
    options: [
      { type: "adventurer", text: "“63 National Parks in One Van: A Retiree's Epic Road Trip”" },
      { type: "creator", text: "“How I Learned Woodturning at 68”" },
      { type: "connector", text: "“The Supper Club That's Been Running for 20 Years”" },
      { type: "sage", text: "“Why Retirees Are Flocking Back to the College Classroom”" },
      { type: "homebody", text: "“From Lawn to Homestead: A Backyard Farm Story”" },
      { type: "competitor", text: "“Meet the 70-Year-Old Pickleball Champion”" },
      { type: "giver", text: "“The Retired Nurse Who's Delivered 40,000 Meals”" },
      { type: "entrepreneur", text: "“She Retired, Then Built a Six-Figure Etsy Shop”" },
    ],
  },
  {
    question: "What's the one thing you refuse to give up in retirement?",
    options: [
      { type: "adventurer", text: "Momentum — always chasing the next trip" },
      { type: "creator", text: "Making things with my hands" },
      { type: "connector", text: "My people — being around others" },
      { type: "sage", text: "Learning something new" },
      { type: "homebody", text: "A sense of home and routine" },
      { type: "competitor", text: "Competition — I like keeping score" },
      { type: "giver", text: "Being useful to somebody" },
      { type: "entrepreneur", text: "Building something that's mine" },
    ],
  },
  {
    question: "Pick a retirement fantasy:",
    options: [
      { type: "adventurer", text: "Renting a scooter in a country I've never seen" },
      { type: "creator", text: "A studio full of half-finished projects" },
      { type: "connector", text: "A house that's always full of people" },
      { type: "sage", text: "A reading chair and an unlimited library card" },
      { type: "homebody", text: "A big garden and bread rising in the kitchen" },
      { type: "competitor", text: "A trophy shelf from the senior league" },
      { type: "giver", text: "A community that leans on me — happily" },
      { type: "entrepreneur", text: "A little business with my name on the door" },
    ],
  },
  {
    question: "What would your friends say about you?",
    options: [
      { type: "adventurer", text: "Always has a trip planned" },
      { type: "creator", text: "Can't sit still without making something" },
      { type: "connector", text: "The one who organizes everything" },
      { type: "sage", text: "Knows a little about everything" },
      { type: "homebody", text: "Happiest at home, hands down" },
      { type: "competitor", text: "Insanely competitive, even at board games" },
      { type: "giver", text: "Would give you the shirt off their back" },
      { type: "entrepreneur", text: "Always has a side hustle going" },
    ],
  },
  {
    question: "Be honest — what would you actually miss about working?",
    options: [
      { type: "adventurer", text: "Nothing — I'll miss having somewhere new to go, not the work" },
      { type: "creator", text: "The craft of doing skilled work well" },
      { type: "connector", text: "The people and the office banter" },
      { type: "sage", text: "Solving genuinely hard problems" },
      { type: "homebody", text: "Honestly? Not much — I love being home" },
      { type: "competitor", text: "Winning, hitting targets, the scoreboard" },
      { type: "giver", text: "Feeling like my work mattered to someone" },
      { type: "entrepreneur", text: "Building something from scratch" },
    ],
  },
];
